### ISSUE TITLE
How do you actually login?

### ISSUE THREAD

**Issue by kalwar** [steliyan123/VLS#1]
There is this username: 'admin'
and password: 

does not accept any password.

Do we need to create mysql database named: vls1?
and enter these USER, PASS values inside?

Please suggest.

**Comment by kalwar** [comment]
Thanks. Found the solution. Had an issue with database creation.
Got it fixed. Sorry for the inconvenience.

**Comment by steliyan123** [comment]
Hi, no inconvenience whatsoever, sorry for seeing this so late.
Its still very buggy and messy but the shiro part works. 
You go register, then make an user and login with it.
Here's a db dump:

usr: pass 
jsmith: jsmith

CREATE TABLE IF NOT EXISTS `users` (
  `user_name` varchar(100) NOT NULL,
  `user_pass` varchar(128) CHARACTER SET utf8 COLLATE utf8_unicode_520_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `users` (`user_name`, `user_pass`) VALUES
('admin', 'eed1be2e97e7c8319c2aa4a22f48abd41bc822ee4f00be1aa7e9d2dc94fc1f30b880ca3454b380dc5a3b72919ffe93ebd7f0d847dd66582c9c1fdfada4e48a93'),
('jsmith', 'b9e2970e4f635294550197ab8d17dac2015f07847c6e6594d67039745f33b55d0f40f2c5f7cea5fac4651ade0b14ee13fdf16b4d0c8a5c6124ed3bd42f15a348'):

CREATE TABLE IF NOT EXISTS `user_roles` (
  `user_name` varchar(100) NOT NULL,
  `role_name` varchar(30) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `user_roles` (`user_name`, `role_name`) VALUES
('jsmith', 'customer'), ('admin', 'admin');

ALTER TABLE `users`
  ADD PRIMARY KEY (`user_name`);

ALTER TABLE `user_roles`
  ADD PRIMARY KEY (`user_name`);

ALTER TABLE `user_roles`
  ADD CONSTRAINT `user_roles_ibfk_1` FOREIGN KEY (`user_name`) REFERENCES `users` (`user_name`);
